#!/bin/bash
# ===========================================================================
# init-gcp.sh — Google Cloud Infrastructure Setup
# Generated by AI Studio Architect (Gemini CLI Skill)
#
# This script provisions all GCP resources required to run an AI Studio
# Build mode application in production. It is idempotent and safe to run
# multiple times.
#
# Usage:
#   chmod +x init-gcp.sh
#   ./init-gcp.sh                    # Execute normally
#   DRY_RUN=true ./init-gcp.sh      # Print commands without executing
#
# Prerequisites:
#   - gcloud CLI installed and authenticated
#   - Billing enabled on the target project
# ===========================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# 1. CONFIGURATION
# Modify these variables for your project.
# ---------------------------------------------------------------------------
PROJECT_ID="${PROJECT_ID:-your-project-id}"
REGION="${REGION:-us-central1}"
SERVICE_NAME="${SERVICE_NAME:-my-app}"
SERVICE_ACCOUNT_NAME="${SERVICE_ACCOUNT_NAME:-${SERVICE_NAME}-sa}"
SERVICE_ACCOUNT_EMAIL="${SERVICE_ACCOUNT_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"

# Storage
BUCKET_NAME="${BUCKET_NAME:-${PROJECT_ID}-${SERVICE_NAME}-assets}"

# Firestore
FIRESTORE_DATABASE="${FIRESTORE_DATABASE:-(default)}"

# Dry run mode
DRY_RUN="${DRY_RUN:-false}"

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------
run() {
  if [ "$DRY_RUN" = "true" ]; then
    echo "[DRY RUN] $*"
  else
    echo "[RUNNING] $*"
    "$@"
  fi
}

section() {
  echo ""
  echo "================================================================"
  echo "  $1"
  echo "================================================================"
}

# ---------------------------------------------------------------------------
# 2. PROJECT SETUP
# Set the active project and verify billing is enabled.
# ---------------------------------------------------------------------------
section "Project Setup"

run gcloud config set project "$PROJECT_ID"

echo "Verifying billing is enabled..."
if [ "$DRY_RUN" != "true" ]; then
  BILLING=$(gcloud billing projects describe "$PROJECT_ID" --format="value(billingEnabled)" 2>/dev/null || echo "false")
  if [ "$BILLING" != "True" ]; then
    echo "ERROR: Billing is not enabled for project $PROJECT_ID."
    echo "Enable it at: https://console.cloud.google.com/billing/linkedaccount?project=$PROJECT_ID"
    exit 1
  fi
  echo "Billing is enabled."
fi

# ---------------------------------------------------------------------------
# 3. ENABLE APIs
# Enable all required Google Cloud APIs. This is idempotent.
# ---------------------------------------------------------------------------
section "Enabling APIs"

APIS=(
  # PLACEHOLDER: The skill will populate this list based on detected services.
  # Example entries:
  # aiplatform.googleapis.com
  # run.googleapis.com
  # firestore.googleapis.com
  # storage.googleapis.com
  # secretmanager.googleapis.com
)

if [ ${#APIS[@]} -gt 0 ]; then
  run gcloud services enable "${APIS[@]}" --project="$PROJECT_ID"
else
  echo "No APIs to enable. Update the APIS array in this script."
fi

# ---------------------------------------------------------------------------
# 4. SERVICE ACCOUNT
# Create a dedicated service account with least-privilege roles.
# Never use the default compute service account in production.
# ---------------------------------------------------------------------------
section "Service Account"

# Create the service account (skip if it already exists)
if ! gcloud iam service-accounts describe "$SERVICE_ACCOUNT_EMAIL" --project="$PROJECT_ID" &>/dev/null; then
  run gcloud iam service-accounts create "$SERVICE_ACCOUNT_NAME" \
    --display-name="${SERVICE_NAME} Service Account" \
    --project="$PROJECT_ID"
  echo "Created service account: $SERVICE_ACCOUNT_EMAIL"
else
  echo "Service account already exists: $SERVICE_ACCOUNT_EMAIL"
fi

# Bind IAM roles
# PLACEHOLDER: The skill will add role bindings based on detected services.
# Example:
# run gcloud projects add-iam-policy-binding "$PROJECT_ID" \
#   --member="serviceAccount:$SERVICE_ACCOUNT_EMAIL" \
#   --role="roles/aiplatform.user" \
#   --condition=None \
#   --quiet

# ---------------------------------------------------------------------------
# 5. CLOUD FIRESTORE
# Create the Firestore database in Native mode.
# ---------------------------------------------------------------------------
# PLACEHOLDER: Uncomment if Firestore is detected.
# section "Cloud Firestore"
#
# if ! gcloud firestore databases describe --project="$PROJECT_ID" &>/dev/null; then
#   run gcloud firestore databases create \
#     --location="$REGION" \
#     --type=firestore-native \
#     --project="$PROJECT_ID"
#   echo "Created Firestore database in $REGION"
# else
#   echo "Firestore database already exists."
# fi

# ---------------------------------------------------------------------------
# 6. CLOUD STORAGE
# Create a storage bucket with CORS configuration for the frontend.
# ---------------------------------------------------------------------------
# PLACEHOLDER: Uncomment if Cloud Storage is detected.
# section "Cloud Storage"
#
# if ! gcloud storage buckets describe "gs://$BUCKET_NAME" &>/dev/null 2>&1; then
#   run gcloud storage buckets create "gs://$BUCKET_NAME" \
#     --location="$REGION" \
#     --uniform-bucket-level-access \
#     --project="$PROJECT_ID"
#   echo "Created bucket: gs://$BUCKET_NAME"
#
#   # Apply CORS configuration
#   cat > /tmp/cors.json << 'CORS_EOF'
# [
#   {
#     "origin": ["*"],
#     "method": ["GET", "PUT", "POST", "DELETE"],
#     "responseHeader": ["Content-Type", "Authorization"],
#     "maxAgeSeconds": 3600
#   }
# ]
# CORS_EOF
#   run gcloud storage buckets update "gs://$BUCKET_NAME" --cors-file=/tmp/cors.json
#   rm /tmp/cors.json
#   echo "Applied CORS configuration to bucket."
# else
#   echo "Bucket already exists: gs://$BUCKET_NAME"
# fi

# ---------------------------------------------------------------------------
# 7. SECRET MANAGER
# Store sensitive values (API keys, credentials) in Secret Manager.
# ---------------------------------------------------------------------------
# PLACEHOLDER: Uncomment if secrets are detected.
# section "Secret Manager"
#
# create_secret() {
#   local secret_name="$1"
#   local description="$2"
#   if ! gcloud secrets describe "$secret_name" --project="$PROJECT_ID" &>/dev/null; then
#     echo "placeholder" | run gcloud secrets create "$secret_name" \
#       --data-file=- \
#       --replication-policy="automatic" \
#       --project="$PROJECT_ID"
#     echo "Created secret: $secret_name (update the value manually)"
#     echo "  gcloud secrets versions add $secret_name --data-file=- --project=$PROJECT_ID <<< 'YOUR_VALUE'"
#   else
#     echo "Secret already exists: $secret_name"
#   fi
# }
#
# create_secret "gemini-api-key" "Gemini API key for Vertex AI"

# ---------------------------------------------------------------------------
# 8. CLOUD RUN
# Deploy the application container to Cloud Run.
# ---------------------------------------------------------------------------
# PLACEHOLDER: Uncomment if Cloud Run is detected.
# section "Cloud Run"
#
# run gcloud run deploy "$SERVICE_NAME" \
#   --source=. \
#   --region="$REGION" \
#   --service-account="$SERVICE_ACCOUNT_EMAIL" \
#   --allow-unauthenticated \
#   --set-env-vars="PROJECT_ID=$PROJECT_ID,REGION=$REGION" \
#   --project="$PROJECT_ID"
#
# SERVICE_URL=$(gcloud run services describe "$SERVICE_NAME" \
#   --region="$REGION" \
#   --format="value(status.url)" \
#   --project="$PROJECT_ID")
# echo "Service deployed at: $SERVICE_URL"

# ---------------------------------------------------------------------------
# 9. OUTPUT SUMMARY
# ---------------------------------------------------------------------------
section "Setup Complete"

echo "Project:          $PROJECT_ID"
echo "Region:           $REGION"
echo "Service Account:  $SERVICE_ACCOUNT_EMAIL"
# echo "Bucket:           gs://$BUCKET_NAME"
# echo "Cloud Run URL:    $SERVICE_URL"
echo ""
echo "Next steps:"
echo "  1. Update secrets in Secret Manager with real values."
echo "  2. Build and deploy your application to Cloud Run."
echo "  3. Configure a custom domain (optional)."
echo "  4. Set up Cloud Monitoring dashboards."
